GET http://localhost:3008/users

###
GET http://localhost:3008/users/1

###
POST http://localhost:3008/users
Content-Type: application/json

{
    "name" : "Beta Nurul",
    "email" : "user@gmail.com",
    "password" : "1234",
    "confPassword" : "1234",
    "role" : "admin"
}

###
POST http://localhost:3008/register
Content-Type: application/json

{
    "name" : "Beta Nurul A",
    "email" : "user@gmail.com",
    "password" : "1234",
    "confPassword" : "1234"
}

###
PATCH http://localhost:3008/users/7
Content-Type: application/json

{
    "name" : "Beta Update2",
    "email" : "user@gmail.com",
    "password" : "1234",
    "confPassword" : "1234",
    "role" : "user"
}

###
DELETE http://localhost:3008/users/2

###
POST http://localhost:3008/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password" : "1234"
}

###
GET http://localhost:3008/me

###
DELETE  http://localhost:3008/logout